const TASKKILL_INVOCATIONS = 2;

export const E2E_PROCESS_TERMINATION_OPTIONS = Object.freeze({
  forceTimeoutMillis: 2000,
  gracefulTimeoutMillis: 2000,
  taskkillTimeoutMillis: 2000,
});

export const E2E_PROCESS_TERMINATION_WORST_CASE_MILLISECONDS =
  E2E_PROCESS_TERMINATION_OPTIONS.gracefulTimeoutMillis +
  E2E_PROCESS_TERMINATION_OPTIONS.forceTimeoutMillis +
  E2E_PROCESS_TERMINATION_OPTIONS.taskkillTimeoutMillis * TASKKILL_INVOCATIONS;

export const E2E_RESOURCE_CLEANUP_HEADROOM_MILLISECONDS = 15_000;
export const E2E_PLAYWRIGHT_SHUTDOWN_TIMEOUT_MILLISECONDS = 30_000;
